{
  "swagger": "2.0",
  "info": {
    "description": "LPT API",
    "version": "1.0.0",
    "title": "LPT Frontend API"
  },
  "basePath": "/web/",
  "tags": [
    {
      "name": "Auth",
      "description": "Аутентификация"
    },
    {
      "name": "Note",
      "description": "Notes Management"
    }
  ],
  "paths": {
    "/auth/register": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Registration",
        "description": "User registration with email and password.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Parameters for registration",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string",
                  "format": "email",
                  "example": "test@test.test",
                  "description": "User email"
                },
                "password": {
                  "type": "string",
                  "format": "password",
                  "example": "Test1234",
                  "description": "User password"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "token": {
                  "type": "string",
                  "description": "JWT token",
                  "example": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9..."
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Login",
        "description": "User login with email and password.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Parameters for login",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string",
                  "format": "email",
                  "example": "test@test.test",
                  "description": "User email"
                },
                "password": {
                  "type": "string",
                  "format": "password",
                  "example": "Test1234",
                  "description": "User password"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "token": {
                  "type": "string",
                  "description": "JWT token",
                  "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/auth/logout": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Logout",
        "description": "User logout.",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful operation"
          },
          "400": {
            "description": "Bad Request"
          }
        },
        "security": [
          {
            "api_key": []
          }
        ]
      }
    },
    "/note/create": {
      "post": {
        "tags": [
          "Note"
        ],
        "summary": "Create Note",
        "description": "Create a new note.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Note data",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "title": {
                  "type": "string",
                  "example": "title",
                  "description": "Note title"
                },
                "content": {
                  "type": "string",
                  "example": "content content content",
                  "description": "Note content"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer",
                  "example": 1,
                  "description": "Note ID"
                },
                "title": {
                  "type": "string",
                  "example": "title",
                  "description": "Note title"
                },
                "content": {
                  "type": "string",
                  "example": "content content content",
                  "description": "Note content"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          }
        },
        "security": [
          {
            "api_key": []
          }
        ]
      }
    },
    "/note/update/{id}": {
      "patch": {
        "tags": [
          "Note"
        ],
        "summary": "Update Note",
        "description": "Update an existing note.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "integer",
            "description": "Note ID"
          },
          {
            "in": "body",
            "name": "body",
            "description": "Updated note data",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "title": {
                  "type": "string",
                  "example": "11111",
                  "description": "Note title"
                },
                "content": {
                  "type": "string",
                  "example": "111111 content content",
                  "description": "Note content"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer",
                  "example": 1,
                  "description": "Note ID"
                },
                "title": {
                  "type": "string",
                  "example": "11111",
                  "description": "Note title"
                },
                "content": {
                  "type": "string",
                  "example": "111111 content content",
                  "description": "Note content"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          }
        },
        "security": [
          {
            "api_key": []
          }
        ]
      }
    },
    "/note": {
      "get": {
        "tags": [
          "Note"
        ],
        "summary": "List Notes",
        "description": "Get a paginated list of notes.",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "required": false,
            "type": "integer",
            "description": "Page number",
            "default": 1
          },
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "type": "integer",
            "description": "Number of items per page",
            "default": 10
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "current_page": {
                  "type": "integer",
                  "example": 1,
                  "description": "Current page"
                },
                "data": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer",
                        "example": 1,
                        "description": "Note ID"
                      },
                      "user_id": {
                        "type": "integer",
                        "example": 1,
                        "description": "User ID"
                      },
                      "title": {
                        "type": "string",
                        "example": "11111",
                        "description": "Note title"
                      },
                      "content": {
                        "type": "string",
                        "example": "111111 content content",
                        "description": "Note content"
                      },
                      "created_at": {
                        "type": "string",
                        "format": "date-time",
                        "example": "2024-06-07T02:39:53.000000Z",
                        "description": "Creation date"
                      },
                      "updated_at": {
                        "type": "string",
                        "format": "date-time",
                        "example": "2024-06-07T03:30:23.000000Z",
                        "description": "Last update date"
                      }
                    }
                  }
                },
                "total": {
                  "type": "integer",
                  "example": 10,
                  "description": "Total number of notes"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          }
        },
        "security": [
          {
            "api_key": []
          }
        ]
      }
    },
    "/note/{id}": {
      "get": {
        "tags": [
          "Note"
        ],
        "summary": "Show Note",
        "description": "Get a single note by ID.",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "integer",
            "description": "Note ID"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer",
                  "example": 1,
                  "description": "Note ID"
                },
                "user_id": {
                  "type": "integer",
                  "example": 1,
                  "description": "User ID"
                },
                "title": {
                  "type": "string",
                  "example": "11111",
                  "description": "Note title"
                },
                "content": {
                  "type": "string",
                  "example": "111111 content content",
                  "description": "Note content"
                },
                "created_at": {
                  "type": "string",
                  "format": "date-time",
                  "example": "2024-06-07T10:45:47.000000Z",
                  "description": "Creation date"
                },
                "updated_at": {
                  "type": "string",
                  "format": "date-time",
                  "example": "2024-06-07T11:00:21.000000Z",
                  "description": "Last update date"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          }
        },
        "security": [
          {
            "api_key": []
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}
